# Generated by Django 3.1.5 on 2021-01-08 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_index_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='index',
            new_name='Contact',
        ),
    ]
